# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tizhong', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u4f53\u91cd')),
                ('juejinzhi', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u6398\u91d1\u503c')),
                ('chengzhangzhi', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u6210\u957f\u503c')),
                ('shengyuzhi', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u751f\u80b2\u503c')),
                ('daishu', models.IntegerField(verbose_name='\u4ee3\u6570')),
                ('image', models.URLField(default='http://p2du8wu7r.bkt.clouddn.com/1.svg', max_length=50, verbose_name='\u5ba0\u7269\u56fe\u7247')),
                ('status', models.CharField(choices=[('chushou', '\u51fa\u552e'), ('shengzhi', '\u751f\u6b96'), ('zhengchang', '\u6b63\u5e38')], default='zhengchang', max_length=50, verbose_name='\u5ba0\u7269\u72b6\u6001')),
                ('jiage', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='\u751f\u80b2\u51fa\u552e\u4ef7\u683c')),
                ('chushengdata', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u51fa\u751f\u65f6\u95f4')),
                ('fuqingid', models.IntegerField(default=0, verbose_name='\u7236\u4eb2id')),
                ('muqingid', models.IntegerField(default=0, verbose_name='\u6bcd\u4eb2id')),
                ('weicishu', models.IntegerField(default=0, verbose_name='\u5582\u98df\u6b21\u6570')),
                ('meitianweishi', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='\u6bcf\u5929\u5582\u98df\u503c')),
                ('shengcishu', models.IntegerField(default=0, verbose_name='\u751f\u80b2\u6b21\u6570')),
                ('shengyushijian', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0b\u6b21\u751f\u80b2\u65f6\u95f4')),
                ('dogname', models.CharField(default=1, max_length=30, verbose_name='\u5ba0\u7269\u540d\u5b57')),
                ('xidaishu', models.DecimalField(decimal_places=4, default=1, max_digits=8, verbose_name='\u7cfb\u4ee3\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='GouMai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muqing', models.IntegerField(verbose_name='\u5356\u65b9id')),
                ('shengyudata', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('shengyunumber', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u8d2d\u4e70\u4ef7\u683c')),
            ],
        ),
        migrations.CreateModel(
            name='JueJin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juejindata', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6398\u91d1\u65f6\u95f4')),
                ('juejinnumber', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u6398\u91d1\u6570\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='ShengYu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muqing', models.IntegerField(verbose_name='\u6bcd\u4eb2id')),
                ('shengyudata', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u751f\u80b2\u65f6\u95f4')),
                ('shengyunumber', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u751f\u80b2\u4ef7\u683c')),
            ],
        ),
        migrations.CreateModel(
            name='WeiShi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weishidata', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5582\u98df\u65f6\u95f4')),
                ('weishinumber', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u5582\u98df\u6570\u91cf')),
                ('weishihash', models.CharField(default=111111111111111111111111111111111111111111L, max_length=60, verbose_name='\u5582\u98dfhash')),
                ('weishizhengzhangtishu', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u5582\u98df\u589e\u4f53\u91cd')),
                ('weishizhengshuxing', models.CharField(choices=[('tizhong', '\u4f53\u91cd'), ('shengyu', '\u751f\u80b2'), ('juejin', '\u6398\u91d1'), ('weizhengjia', '\u672a\u589e\u52a0')], default='weizhengjia', max_length=15, verbose_name='\u589e\u52a0\u5c5e\u6027')),
                ('weishizhengshuxingzhi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u5582\u98df\u589e\u5c5e\u6027\u503c')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.CatInfo', verbose_name='\u732b')),
            ],
        ),
    ]
