# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shengyu',
            name='fuqing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7236\u4eb2id'),
        ),
        migrations.AddField(
            model_name='juejin',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.CatInfo', verbose_name='\u732b'),
        ),
        migrations.AddField(
            model_name='goumai',
            name='fuqing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u65b9id'),
        ),
        migrations.AddField(
            model_name='catinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e3b\u4eba'),
        ),
    ]
